name: file-roller
version: 3.24.1
summary: An archive manager for GNOME.
description: |
  File Roller is an archive manager for the GNOME environment.  This means that 
  you can : create and modify archives; view the content of an archive; view a 
  file contained in the archive; extract files from the archive.
  File Roller is only a front-end (a graphical interface) to archiving programs 
  like tar and zip. The supported file types are :
    * 7-Zip Compressed File (.7z)
    * WinAce Compressed File (.ace)
    * ALZip Compressed File (.alz)
    * AIX Small Indexed Archive  (.ar)
    * ARJ Compressed Archive (.arj)
    * Cabinet File (.cab)
    * UNIX CPIO Archive (.cpio)
    * Debian Linux Package (.deb) [Read-only mode]
    * ISO-9660 CD Disc Image (.iso) [Read-only mode]
    * Java Archive (.jar)
    * Java Enterprise archive (.ear)
    * Java Web Archive (.war)
    * LHA Archive (.lzh, .lha)
    * WinRAR Compressed Archive (.rar)
    * RAR Archived Comic Book (.cbr)
    * RPM Linux Package (.rpm) [Read-only mode]
    * Tape Archive File:
          * uncompressed (.tar) 
      or compressed with:
          * gzip (.tar.gz , .tgz)
          * bzip (.tar.bz , .tbz)
          * bzip2 (.tar.bz2 , .tbz2)
          * compress (.tar.Z , .taz)
          * lzip (.tar.lz , .tlz)
          * lzop (.tar.lzo , .tzo)
          * 7zip (.tar.7z)
          * xz (.tar.xz)
    * Stuffit Archives (.bin, .sit)
    * Windows Imaging Format (.wim, .swm)
    * ZIP Archive (.zip)
    * ZIP Archived Comic Book (.cbz)
    * ZOO Compressed Archive File (.zoo)
    * Single files compressed with gzip, bzip, bzip2, compress, lzip, lzop, 
      rzip, xz.

icon: data/icons/256x256/apps/file-roller.png

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

# libgdk is linked with libmirclient, which seems to be specifically
# excluded from the snap in favour of the mir-libs snap.
plugs:
  mir-libs:
    interface: content
    content: mir0
    target: mir-libs
    default-provider: mir-libs

apps:
  file-roller:
    command: desktop-launch $SNAP/bin/file-roller
    plugs:
      - x11
      - home
      - gsettings
      - mir-libs

parts:
  fileroller:
    after:
      - desktop-gtk3
    plugin: autotools
    source: .
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/mir-libs

    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - intltool
      - libarchive-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libjson-glib-dev
      - libmagic-dev
      - libnotify-dev
      - yelp-tools
